import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getAllInsights } from '../lib/insights';

const generatedFilePath = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'lib',
  'generated',
  'insight-articles.ts',
);

const articleRootPrefixes = [
  'presentations/write-code-ai-agents-love/research/insights/',
  'presentations/voice-agents/research/drafts/',
] as const;

function normalizeArticlePath(articlePath: string) {
  return normalize(articlePath).replaceAll('\\', '/');
}

function validateArticlePath(articlePath: string) {
  const normalizedArticlePath = normalizeArticlePath(articlePath);
  const articleRootPrefix = articleRootPrefixes.find((prefix) => {
    return normalizedArticlePath.startsWith(prefix);
  });

  if (!articleRootPrefix) {
    throw new Error(`Invalid insight article path: ${articlePath}`);
  }

  const articleFileName = normalizedArticlePath.slice(articleRootPrefix.length);

  if (
    !articleFileName.endsWith('.md') ||
    articleFileName.includes('/') ||
    articleFileName.startsWith('.')
  ) {
    throw new Error(`Invalid insight article filename: ${articlePath}`);
  }

  return normalizedArticlePath;
}

const articlePaths = Array.from(
  new Set(
    getAllInsights()
      .map((insight) => insight.articlePath)
      .filter((articlePath): articlePath is string => Boolean(articlePath)),
  ),
).sort();

const insightArticles = Object.fromEntries(
  articlePaths.map((articlePath) => {
    const normalizedArticlePath = validateArticlePath(articlePath);
    const markdown = readFileSync(join(process.cwd(), normalizedArticlePath), 'utf8');

    return [normalizedArticlePath, markdown];
  }),
);

const generatedSource = `// This file is generated by scripts/generate-insight-articles.ts.
// Do not edit manually.

export const insightArticles: Record<string, string> = ${JSON.stringify(insightArticles, null, 2)};
`;

mkdirSync(dirname(generatedFilePath), { recursive: true });
writeFileSync(generatedFilePath, generatedSource);

console.log(`Generated ${articlePaths.length} insight articles.`);
